### ISSUE TITLE
Provide datasets used for training

### ISSUE THREAD

**Issue by ascheman** [2ral/Modelizer#2]
I was able to fix #1 locally. However, it turned out that at least the two executables on the top level of the project are missing files which should be provided in a `dataset` folder, cf.

- https://github.com/2ral/Modelizer/blob/a88a3bd0504dbe514f973c00d082a227ec39a5f2/train_all_datasets.sh#L9-L24
- https://github.com/2ral/Modelizer/blob/a88a3bd0504dbe514f973c00d082a227ec39a5f2/train_all_subjects.sh#L9-L13

Without further investigation it looks like there are more files missing, cf.

- https://github.com/2ral/Modelizer/blob/a88a3bd0504dbe514f973c00d082a227ec39a5f2/train_all_subjects.sh#L14-L22, i.e., `sources`, which seem to be used for missing files in `models` in
- https://github.com/2ral/Modelizer/blob/master/scripts/model-train.py

**Comment by 2ral** [comment]
Dear Gerd Aschemann,

I appreciate your interest in the Modelizer framework. 
The replication package with all required training datasets and trained models will be uploaded soon on Zenodo. We will include the link in the README. Sorry for the inconvenience. It takes a bit more time than we were initially expecting.

Best wishes,
Tural

**Comment by 2ral** [comment]
Dear Gerd Aschemann,

The dataset is uploaded to Zenodo. You can download it via [https://zenodo.org/records/12742928](https://zenodo.org/records/12742928). 
We also added the basic instructions on repeating the experiments with the provided data. 
I am going to close this issue now as it was resolved.

Best wishes,
Tural
